name: SLPM_654.95
sha1: 0e6b14fe1f1665313ee3dac87304fcd02816ce44
options:
  basename: SLPM_654.95
  target_path: SLPM_654.95
  base_path: ..
  
  #compiler
  platform: ps2
  compiler: MWCCPS2
  
  asm_path: asm/main
  src_path: src/main
  build_path: build

  extensions_path: tools/splat_ext
  symbol_addrs_path: [config/main_symbol_addrs.txt, config/main_shims_addrs.txt]
  undefined_funcs_auto_path: config/undefined_funcs_auto.txt
  undefined_syms_auto_path: config/undefined_syms_auto.txt

  find_file_boundaries: False #funcs are already aligned?
  string_encoding: SHIFT-JIS
  rodata_string_guesser_level: 2
  disasm_unknown: True
  gp_value: 0x0038EB70

  asm_function_macro: .fn
  asm_data_macro: .obj
  asm_nonmatching_label_macro: ""
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */

  section_order: [".text", ".vutext", ".data", ".vudata", ".rodata", ".init", ".ctor", ".vtables", ".sdata", ".sbss", ".bss", ".common", ".vubss"]
segments:
  - [0x0, databin, elf/mainheader]
  #- [0x34, databin, elf/programheadertable]
  - name: main
    type: code
    start: 0x180
    vram: 0x100000
    bss_size: 0x1A9900
    subsegments:
    - [0x180, asm, crt0]
    - [0x3b0, asm, ../lib/cri/adx_init]
    - [0xfa0, c, cardinit]
    - [0x1010, asm, eft]
    - [0x9fb0, asm, em]
    - [0xeda0, asm, fade]
    - [0xf1d0, asm, game]
    - [0x1cf70, asm, item]
    - [0x1dc90, asm, light]
    - [0x1e9e0, asm, tex]
    - [0x1eea0, asm, load]
    - [0x1f570, asm, main]
    - [0x203c0, asm, math]
    - [0x21110, asm, parts]
    - [0x214b0, asm, yure]
    - [0x21cf0, asm, model]
    - [0x251e0, asm, scheduler]
    - [0x254c0, asm, motion]
    - [0x26940, asm, option]
    - [0x275c0, asm, cockpit]
    - [0x34bc0, asm, player]
    - [0x55020, asm, heap]
    - [0x55660, asm, info]
    - [0x590a0, asm, shell]
    - [0x59550, asm, softdip]
    - [0x59590, asm, sound]
    - [0x5a6a0, asm, sprite]
    - [0x5bc30, c, stage]
    - [0x61370, asm, system]
    # - [0x, asm, tex]
    - [0x63c30, asm, trans]
    - [0x64280, asm, weapon]
    - [0x67a40, asm, unk]
    - [0x693b0, asm, prim]
    - [0x69930, asm, vib]
    - [0x69b20, asm, view]
    - [0x6a320, asm, em_work]
    - [0x6ad20, asm, fl]
    - [0x8f240, asm, pl]
    - [0x94b80, asm, ps2]
    - [0x964b0, asm, ../lib/sce/sce_hw]
    - [0x99900, asm, util]
    - [0xa96b8, asm, ../lib/sce/sceGs]
    - [0xaa078, asm, ../lib/sce/sceIpu]
    - [0xaf6e0, asm, ../lib/sce/sceMc]
    - [0xb2c28, asm, ../lib/sce/sceMpeg]
    - [0xb7e28, asm, ../lib/sce/scePad2]
    - [0xb8720, asm, ../lib/sce/sceVib]
    - [0xb8890, asm, ../lib/sce/sceVu0]
    - [0xb9fe0, asm, mwInit]
    - [0xba0f0, asm, netsync]
    - [0xbd7e0, asm, sfd]
    - [0xbdce8, asm, ../lib/CFT]
    - [0xc4d08, asm, ../lib/M2V]
    - [0xf3620, asm, ../lib/ADX]
    - [0x108678, asm, ../lib/SRD]
    - [0x1099b8, asm, ../lib/DTR]
    - [0x109ff8, asm, ../lib/UNKLIB]
    # DTX, [...], pl2(pro logic 2), RNA, SJMEM, SJRBF, SJUNI, SVM, sdr(1142e0), flsnd
    - [0x116610, asm, flfnt]
    - [0x117fd0, asm, plAPX]
    - [0x118710, asm, eft20]
    - [0x11d5f0, asm, bgm]
    - [0x11f550, asm, camera]
    - [0x126140, asm, set21]
    - [0x126970, asm, quest]
    - [0x12c7e0, asm, CngInet]
    #- [0x12cd70, asm, AQ]
    - [0x12f930, asm, movie]
    - [0x12ff50, asm, entry]
    - [0x12ff80, asm, InetMcs]
    - [0x132dd0, asm, ../lib/sce/sceSif]
    - [0x133c90, asm, Ave]
    - [0x136a40, asm, ../lib/sce/sceNetGlue]
    - [0x137920, asm, InetDNS]
    - [0x138070, asm, InetConnect]
    - [0x13a270, asm, modesel]
    - [0x13b630, asm, omake]
    - [0x13c188, asm, ../lib/sce/sceUsbKb]
    - [0x13d9f0, asm, npc]
    - [0x13e680, asm, overlays]
    - [0x13e7b0, asm, textinput]
    - [0x14a3c0, asm, effect]
    - [0x154480, asm, scekernel]
    - [0x15fb00, asm, softkey]
    - [0x167320, asm, netOverlay]
    - [0x172020, asm, userdata]
    - [0x174f90, asm, interface]
    - [0x17c230, asm, ../lib/sce/sceScf]
    - [0x17cbd0, asm, eft26]
    - [0x17d090, asm, cnLBS_download]
    - [0x17d860, asm, eft02]
    - [0x17f0e0, asm, save]
    - [0x186470, asm, demo]
    - [0x186b20, asm, netfile]
    - [0x18cdc0, asm, hitcoll]
    - [0x190940, asm, staff]
    - [0x190de0, asm, poweroff]
    - [0x190fd0, asm, result]

    - [0x193D00, data, vutext]

    #- [0x1E6020, data, data]
    - [0x1e6020, data, ../lib/CRI/adx_init]
    - [0x1e61c0, data, eft]
    - [0x1e8310, data, em]
    - [0x1e8540, data, fade]
    - [0x1e86a0, data, game]
    - [0x1e8880, data, item]
    - [0x1e8dc0, data, light]
    - [0x1ebdd0, data, load]
    - [0x1ed210, data, tex]
    - [0x1ef510, data, yure]
    - [0x1ef7d0, data, model]
    - [0x1ef940, data, option]
    - [0x1ef9c0, data, cockpit]
    - [0x1f0f98, data, player]
    - [0x1f1fd0, data, sound]
    - [0x1f2780, data, stage]
    - [0x2007a0, data, system]
    - [0x200920, data, weapon]
    - [0x201b60, data, vib]
    - [0x201b90, data, view]
    - [0x201bc0, data, fl]
    - [0x206680, data, ps2]
    - [0x2067c0, data, ../lib/sce/sce_hw]
    - [0x2083c8, data, util]
    - [0x208b40, data, ../lib/sce/sceGs]
    - [0x208b80, data, ../lib/sce/sceIpu]
    - [0x208c00, data, ../lib/sce/sceMc]
    - [0x208c60, data, ../lib/sce/sceMpeg]
    - [0x208d80, data, ../lib/sce/scePad2]
    - [0x208db0, data, ../lib/sce/sceVu0]
    - [0x208df0, data, ../lib/CFT]
    - [0x20bdf8, data, ../lib/M2V]
    - [0x20c2d8, data, sfd]
    - [0x20df80, data, ../lib/ADX]
    - [0x21e8a0, data, ../lib/CVFS]
    - [0x21e8b0, data, ../lib/SRD]
    - [0x21e928, data, ../lib/DTR]
    - [0x21f900, data, ../lib/UNKLIB] #dvg ci.... im lazy
    - [0x22d460, data, flfnt]
    - [0x22d5f0, data, bgm]
    - [0x22db80, data, em_cmd] #in game.bin
    - [0x22df70, data, eft20]
    - [0x231000, data, userdata]
    - [0x233a50, data, interface]
    - [0x239050, data, camera]
    - [0x2395b8, data, set21]
    - [0x239620, data, quest]
    - [0x23b1e0, data, CngInet]
    - [0x248fb0, data, movie]
    - [0x249040, data, InetMcs]
    - [0x249070, data, ../lib/sce/sceSif]
    - [0x249180, data, InetConnect]
    - [0x249390, data, modesel]
    - [0x249510, data, omake]
    - [0x249548, data, ../lib/sce/sceUsbKb]
    - [0x2495b0, data, npc]
    - [0x249680, data, overlays]
    - [0x2496a0, data, textinput]
    - [0x24aea0, data, scekernel]
    - [0x24c590, data, softkey]
    - [0x24f720, data, netOverlay]
    - [0x251910, data, userdata2]
    - [0x251a30, data, interface2]
    - [0x254e10, data, ../lib/sce/sceScf]
    - [0x254f50, data, eft26]
    - [0x254f80, data, eft02]
    - [0x254fd0, data, save]
    - [0x2555e0, data, demo]
    - [0x2556a0, data, netfile]
    - [0x255780, data, staff]
    - [0x256a90, data, em_meat]
    - [0x257790, data, quest_table]
    - [0x257a58, data, result]

    - [0x257b00, rodata, ../lib/CRI/adx_init]
    - [0x257b40, rodata, eft]
    - [0x257f20, rodata, em]
    - [0x2581f0, rodata, game]
    - [0x258560, rodata, model]
    - [0x258658, rodata, option]
    - [0x258930, rodata, cockpit]
    - [0x25a910, rodata, player]
    - [0x25b940, rodata, info]
    - [0x25b990, .rodata, stage]
    - [0x25bb80, rodata, system]
    - [0x25bca0, rodata, trans]
    - [0x25bd60, rodata, weapon]
    - [0x25bdd0, rodata, fl]
    - [0x25c2c0, rodata, pl]
    - [0x25c310, rodata, ps2]
    - [0x25c3f8, rodata, ../lib/sce/sce_hw]
    - [0x25c900, rodata, util]
    - [0x25d9a8, rodata, ../lib/sce/sceGs]
    - [0x25dc98, rodata, ../lib/sce/sceIpu]
    - [0x25e770, rodata, ../lib/sce/sceMc]
    - [0x25e898, rodata, ../lib/sce/sceMpeg]
    - [0x25ed30, rodata, ../lib/sce/scePad2]
    - [0x25ed90, rodata, netsync]
    - [0x25ee68, rodata, ../lib/CFT]
    - [0x25ef10, rodata, ../lib/M2V]
    - [0x2621e0, rodata, ../lib/ADX]
    - [0x264788, rodata, ../lib/CVFS]
    - [0x265440, rodata, ../lib/SRD]
    - [0x2657d0, rodata, ../lib/DTR]
    - [0x265a30, rodata, ../lib/DVCI]
    - [0x265e00, rodata, ../lib/HTCI]
    - [0x266318, rodata, ../lib/LSC]
    - [0x2668c0, rodata, ../lib/pl2]
    - [0x266ac8, rodata, ../lib/RNA]
    - [0x267020, rodata, ../lib/SJ]
    - [0x267190, rodata, ../lib/SVM]
    - [0x267340, rodata, sdr]
    - [0x267370, rodata, flsnd]
    - [0x267430, rodata, eft20]
    - [0x267630, rodata, bgm]
    - [0x267660, rodata, unk]
    - [0x26b250, rodata, camera]
    - [0x26b2f8, rodata, quest]
    - [0x26b598, rodata, item]
    - [0x26ca18, rodata, AQ]
    - [0x26cb30, rodata, ../lib/sce/sceSif]
    - [0x26ce30, rodata, CngInet]
    - [0x26d110, rodata, modesel]
    - [0x26d378, rodata, ../lib/sce/sceUsbKb]
    - [0x26e1b0, rodata, textinput]
    - [0x26e240, rodata, effect]
    - [0x26e288, rodata, scekernel]
    - [0x26e5d0, rodata, softkey]
    - [0x270820, rodata, netOverlay]
    - [0x273670, rodata, userdata]
    - [0x273780, rodata, interface]
    - [0x284260, rodata, ../lib/sce/sceScf]
    - [0x2842d0, rodata, cnLBS_download]
    - [0x2842f0, rodata, eft02]
    - [0x2843c0, rodata, save]
    - [0x285208, rodata, netfile]
    - [0x285248, rodata, staff]
    - [0x286590, rodata, poweroff]
    - [0x2865b0, rodata, result]
    - [0x286c80, rodata, overlayoffs]

    - [0x286d00, sdata, ../lib/CRI/adx_init]
    - [0x286d08, sdata, eft]
    - [0x286d38, sdata, game]
    - [0x286d40, sdata, item]
    - [0x286d50, sdata, load]
    - [0x287824, sdata, tex]
    - [0x287840, sdata, main]
    - [0x287848, sdata, model]
    - [0x287880, sdata, option]
    - [0x287898, sdata, cockpit]
    - [0x2878f0, sdata, yure]
    - [0x2878f8, sdata, player]
    - [0x287914, sdata, stage]
    - [0x287a78, sdata, system]
    - [0x287aa0, sdata, trans]
    - [0x287ad8, sdata, fl]
    - [0x287ae0, sdata, ../lib/ps2]
    - [0x287af0, sdata, ../lib/ADX]
    - [0x287b00, sdata, eft20]
    - [0x287b70, sdata, bgm]
    - [0x287b78, sdata, set21]
    - [0x287b88, sdata, quest]
    - [0x287b94, sdata, CngInet]
    - [0x287bd4, sdata, movie]
    - [0x287bd8, sdata, InetMcs]
    - [0x287bf0, sdata, modesel]
    - [0x287bf8, sdata, overlays]
    - [0x287c00, sdata, textinput]
    - [0x287c48, sdata, netOverlay]
    - [0x287d90, sdata, interface]
    - [0x287e00, sdata, save]
    - [0x287e50, sdata, netfile]
    - [0x287e58, sdata, quest_table]
    - [0x287ea8, sdata, result]
    - [0x287eb8, sdata, gamebin_stragglers]
    - [0x289f30, sdata, ynbin_stragglers]
    - [0x289fd8, sdata, lobbybin_stragglers]
    - [0x28a1a8, sdata, dnasbin_stragglers]

    - {vram: 0x38a080, type: sbss, name: ../lib/cri/adx_init}
    - {vram: 0x38a090, type: sbss, name: eft}
    - {vram: 0x38a09c, type: sbss, name: game}
    - {vram: 0x38a0ac, type: sbss, name: item}
    - {vram: 0x38a0b8, type: sbss, name: tex}
    - {vram: 0x38a0bc, type: sbss, name: main}
    - {vram: 0x38a0c0, type: sbss, name: cockpit}
    - {vram: 0x38a0cc, type: sbss, name: heap}
    - {vram: 0x38a0d8, type: sbss, name: info}
    - {vram: 0x38a0e4, type: sbss, name: shell}
    - {vram: 0x38a0f0, type: sbss, name: sound}
    - {vram: 0x38a0f8, type: sbss, name: sprite}
    - {vram: 0x38a104, type: sbss, name: trans}
    - {vram: 0x38a110, type: sbss, name: view}
    - {vram: 0x38a114, type: .sbss, name: stage}
    - {vram: 0x38a11c, type: sbss, name: unsorted}

    - {vram: 0x38AA54, type: bss, name: ..lib/cri/adx_init }
    - {vram: 0x390880, type: .bss, name: cardinit}
    - {vram: 0x390910, type: bss, name: eft}
    - {vram: 0x392b10, type: bss, name: fade}
    - {vram: 0x392b20, type: bss, name: bss_1}
    - {vram: 0x3d8230, type: .bss, name: stage }
    - {vram: 0x3d82a0, type: bss, name: bss_2 }
    - {vram: 0x531740, type: bss, name: memcard}
    - {vram: 0x531910, type: bss, name: bss_3}
  - [0x28A200, databin, elf/shstrtab]
  - [0x28A320, databin, elf/strtab]
  - [0x333C30, databin, elf/symtab]
  - [0x3F7AB0, databin, elf/mwcats0x3f7ab0]
  - [0x3FE090, databin, elf/mwcats0x3fe090]
  - [0x3FE200, databin, elf/mwcats0x3fe200]
  - [0x4036B0, databin, elf/mwcats0x4036b0]
  - [0x403A30, databin, elf/mwcats0x403a30]
  - [0x4079D0, databin, elf/mwcats0x4079d0]
  - [0x407A00, databin, elf/mwcats0x407a00]
  - [0x407A20, databin, elf/relmain]
  - [0x4995E0, databin, elf/relselect]
  - [0x49B450, databin, elf/relgame]
  - [0x4E18F0, databin, elf/relyn]
  - [0x4E6600, databin, elf/rellobby]
  - [0x540B20, databin, elf/reldnas_net]
  - [0x55B6B0, databin, elf/reldnas_ins]
  - [0x562D40, databin, elf/comment]
  - [0x562D6C, databin, elf/reginfo]
  - [0x562D84, databin, elf/sectionheadertable]
  - [0x56320C] #eof
