

sha1: a646083b86e08ff0e79b0ddbd96a940893d5b53c
options:
  basename: select
  base_path: ..
  target_path: overlays/select.bin
  
  #compiler
  platform: ps2
  compiler: MWCCPS2
  
  asm_path: asm/overlay/select
  src_path: src/overlay/select
  build_path: build
  
  extensions_path: tools/splat_ext
  symbol_addrs_path: [config/select_symbol_addrs.txt, config/main_symbol_addrs.txt]
  undefined_funcs_auto_path: config/select_funcs_auto.txt
  undefined_syms_auto_path: config/select_syms_auto.txt

  find_file_boundaries: False #funcs are already aligned?
  string_encoding: SHIFT-JIS
  rodata_string_guesser_level: 2
  disasm_unknown: True
  gp_value: 0x0038EB70

  asm_function_macro: .fn
  asm_data_macro: .obj
  asm_nonmatching_label_macro: ""
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */

  section_order: [".text", ".vutext", ".data", ".vudata", ".rodata", ".init", ".ctor", ".vtables", ".sbss", ".bss", ".common", ".vubss"]


segments:
  - [0x0, databin, select_header]
  - name: select
    type: code
    start: 0x80
    vram: 0x533A00
    bss_size: 0x0
    subsegments:
    - [0x80, asm, select_code]

    - [0x4D80, data, select_data]

  - [0x8000] #eof
